services:

  # db service
  db:
    container_name: db_guesser_yt
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 5

  # flask service
  flaskapp:
    container_name: flaskapp_guesser_yt
    image: flaskapp_guesser_yt:1.0.0
    build:
      context: ./backend
      dockerfile: flask.dockerfile
    ports:
      - 4000:4000
    environment:
      FLASK_APP: run.py
      DATABASE_URL: postgresql://postgres:postgres@db_guesser_yt:5432/postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]  # Adjust the endpoint as necessary
      interval: 20s
      timeout: 20s
      retries: 5

  # nextjs service
  nextapp:
    container_name: nextapp_guesser_yt
    image: nextapp_guesser_yt:1.0.0
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  pgdata: {}