services:
  # db service
  db-dev:
    image: postgres:16
    container_name: viddle-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - dev-db

  # flask service
  viddle-backend:
    container_name: viddle-backend
    build:
      context: ../
      dockerfile: ./backend/express.dockerfile
    ports:
      - 4001:4000
    volumes:
      - ./:/app/backend
    networks:
      - dev-db

networks:
  dev-db:
