export const SUGGESTIONS = [
    "Livestream highlight video",
    "Genuinely good video",
    "Attaches microphone to some utensil",
    "Impressive editing",
    "Minecraft",
    "\"this shouldn\'t have been made public\"",
    "fecal funny",
    "Music cuts or quietens as the creator says a joke punchline in a weak and low voice",
    "Over-blown mouth when a person is screaming",
    "Makes significant other do something the creator is interested in",
    "\"maybe i\'m not in the right demographic for this kind of video\"",
    "TV static buzz with coloured bars upon a video cut",
    "Sports",
    "Edit of some character(s) from popular media being inside a video game",
    "Podcast",
    "Makes AI make the content rather than the creator themselves",
    "Stick figure",
    "haha t-pose",
    "haha a-pose",
    "haha stock image",
    "Tech YouTuber wears a front-facing snapback hat",
    "At the start, creator slowly gets into position to speak into the microphone in front of the camera, then says a certain word or phrase to transition to their video\'s next section",
    "[social media post/topic] reading video",
    "JCS clone",
    "When emphasizing a phrase, video cuts to a closer capture of an entity on each emphasis",
    "Soundfont switch",
    "Wii (shop included) and/or Animal Crossing music",
    "Reaction video",
    "Commercial",
    "Complains about the equal enforcement of rules on a platform",
    "Mentions the word \"parasocial\"",
    "touhou",
    "forsen",
    "Creator films themself doing a good thing",
    "British video essayist",
    "Verbose doesn't equal eloquence",
    "Tutorial that only gets to the point near the end of the video",
    "Speedrunner",
    "Politics",
    "the game/movie isn\'t even out yet, dude.",
    "Sexually suggestive",
    "Creator asks a group of people to play a game with slightly different rules",
    "Old video (at least 10 yrs old)",
    "Travel vlogger",
    "Hides an overt political message",
    "Foreigner fluently speaks the same language as the foreign country they\'re in",
    "Weaboo",
    "Whataboutism",
    "Young person rants about loneliness, how society bad, and/or nihilism",
    "\"[Entire piece of media] but [slight edit]\"",
    "Mr. Beast text",
    "Old Pewdiepie text",
    "Something about how a popular game is better than big bad corpo games",
    "Uses gay as an insult",
    "Gay",
    "A YTPMV that is excessively cluttered with sources and soundbites",
    "Jump cuts or zooms in on a face after something reaction-worthy occurs",
    "Young person cuts after almost every sentence spoken",
    "Uses the \"gigachad\" image",
    "Subtitles in the middle with two videos: one on top and the other on the bottom",
    "69 haha funny",
    "Editing mistake (including audio)",
    "Jumpscare",
    "Video essay begins with something like \"Since the beginning of time...\"",
    "Streamer purposely says/does something weird to trigger disgusted and confused reactions from the people around them",
    "Freeboot",
    "Uses the word \"insane\", \"bizarre\" or any similar variations",
    "Furry",
    "Talks about killing themselves",
    "Young person makes a self-deprecating joke",
    "Young person talks about how something quirky/silly is keeping them sane",
    "\"Old good, new bad\"",
    "Awkward moment accompanied by a jump cut zoom in/out of the spokesperson",
    "Border around a shown video/image",
    "Dubstep",
    "List video",
    "Camera shake effect around a shown video/image",
    "Neon sign of username",
    "Porn acting",
    "Video zooms out awkwardly with a black background while the creator talks, seemingly getting sidetracked",
    "Mukbang",
    "haha 420",
    "\"I made my viewers do [activity]\"",
    "Video essayist says something obvious but acts like it\'s a groundbreaking revelation",
    "Lo-fi music",
    "Vaporwave",
    "Metal pipe",
    "Filmed to be a short, but is actually a video",
    "Pretentious film student",
    "Creator briefly advertises their course during a tutorial",
    "Young person giving life advice intended for impressionable adolescents",
    "[music genre] mix",
    "Animal compilation",
    "Sponsor in the middle of the video",
    "Quack sound effect",
    "ASMR",
    "Voice actor funnily reads social media post",
    "Unboxing or card opening",
    "Animation that's way too expressive with hand and body movements",
    "Young person trying too hard to be edgy",
    "Shows YouTube from the yellow subscribe buttond days",
    "YouTube short or TikTok subtitles",
    "Stop shouting",
    "Complains about YouTube",
    "Creator does wacky thing and is somehow surprised by wacky result",
    "Outdated meme",
    "Top text, bottom video",
    "Young person talking about their political views",
    "Impact font voice acting video",
    "Adult rants about a children\'s show for 20+ minutes",
    "Young person covers their entire face while talking to the camera",
    "Caribou",
    "Uses wojacks and/or rage comics unironically",
    "[generation name] fear mongering",
    "Applies a topic to a specific generation, but could really apply to any kind of person",
    "AI fear mongering",
    "When talking about COVID-19, uses the word \"unprecedented\"",
    "Seems to support one side more than the other, despite claiming to be unbiased",
    "Old person engages in pastime typically associated with younger people",
    "Hand cam",
    "Foreign language",
    "Shy animator",
    "A click sound effect, followed by a bell sound effect",
    "A snippet of mouse cursor clicking a subscribe button or bell icon",
    "Animator with a cutesy, bubbly art style",
    "Young person word transformation (eg. “Thicc” instead of “Thick” or “Doe”)",
    "Young person terminology",
    "Creator vocally questions why they included something in their script",
    "\"Deal with it\" sunglasses",
    "Late night show",
    "Video is a supposed message to a renowned employee or company",
    "Collab",
    "Creator has to explicitly tell viewers not to harass someone",
    "Music video",
    "Speedrun",
    "Creator rants about something tangentially related to the video topic",
    "Nightcore",
    "Video is x2 speedable",
    "Creator is surprised by how difficult a daily normal activity is",
    "Creator talks/rants for a meandering period of time while the video zooms in on a screencap of the video\'s target",
    "Fair use disclaimer",
    "TMZ",
    "what the fuck is happening",
    "\"good point, but i've already depicted you as the bad guy in my youtube skit\"",
    "Joke doesn\'t land",
    "Smexual",
    "About the downfall of someone no one probably cares about",
    "Quirky humour",
    "Cat",
    "VTuber",
    "Facecam covers the entire screen",
    "Skit involving 1-2 real people: one person does a wacky thing and the other reacts to the person\'s wackiness exaggeratedly",
    "Overly enthusiastic vlogger",
    "Overly cynical commentator",
    "[Social media] user shaming",
    "Video game OST",
    "\"I didn't want to make this video\"",
    "Roleplayer",
    "Excessive vulgarity",
    "Broccoli ass haircut",
    "Swoosh sound effect",
    "The video creator uses text-to-speech to talk",
    "The video creator only uses on-screen text to talk",
    "Just straight up gameplay",
    "Rants about how bad a piece of media for 20+ minutes",
    "Talks about capitalism",
    "Meme compilation",
    "Mentions the algorithm",
    "Says the word \"guys\"",
    "Giveaway",
    "Something about quitting social media",
    "Something about committing war crimes",
    "Young person uses a handheld microphone while flailing their arms wildly",
    "Unregistered hypercam 2",
    "Mentions ad revenue",
    "Creator holding a handheld microphone talks about how problematic a piece of media or event is for 20+ mins",
    "Kinemaster",
    "Flipaclip",
    "ibisPaint",
    "Alight motion",
    "Gacha Life",
    "Talks about a story from school",
    "Calls something woke",
    "Sturgeon\'s Law",
    "High pitched voice",
    "Vine boom sound effect",
    "Japanese voice synthesizer",
    "Laughing sound effect",
    "\"Tries to emulate “old YouTube\"",
    "Points a gun at you",
    "Young person doing a cover of a sad song while legit acting depressed",
    "Mentions sanity",
    "Talks about how the education system is bad, especially if it mentions how it teaches students to memorize rather than learn",
    "Kevin MacLeod",
    "This is just porn",
    "Cover song where the singer really wants you to think they sound good",
    "Good vocalist",
    "Iceberg video",
    "Cooking",
    "Screen shakes when an entity yells",
    "Quirky girl quirkily plays the quirky ukulele",
    "Personality astrology",
    "Hashtags",
    "Trailer and/or teaser",
    "Creator is shocked by the disturbing AI creations that the creator tells it to make",
    "Alludes to a more serious word or phrase by using a dumb replacement",
    "Something about absurdism",
    "Young person pretentiously talks about finding meaning in life",
    "Funny moments compilation",
    "Let\'s player",
    "Down bad",
    "Creator talks while a video is behind them or is quite literally projected onto them",
    "I don\'t care",
    "Mentions something related to IQ or brain cells",
    "Stock footage",
    "Mentions something being \"unhinged\"",
    "Zoom in shot transition",
    "Creator pretends to be a novice at something but then surprises a teacher with how good they are minutes later",
    "AI song cover",
    "AI voiceover",
    "Overly religious with motivational music",
    "Animation",
    "Animation \"meme\"???",
    "VHS visual effect",
    "\"i paid someone to do my job for me\"",
    "Ironic comic sans",
    "Hyperbole",
    "VHS insertion sound effect",
    "Video game",
    "Earrape",
    "Creator puts their face/logo over a stock image of a person",
    "Video essay on some obscure media that they really want me to care about",
    "Something to do with taking drugs",
    "Half-Life SFX",
    "Zooms in on facecam when something notable happens or when the subject speaks",
    "Ding sound effect",
    "Title is roundabout in mentioning the video creator themself",
    "Title asks a very vague question that no sensible person would have asked",
    "In the title, a noun is in all caps",
    "In the title, a verb is in all caps",
    "Title ellipses",
    "Title ends in a file extension",
    "Talks about a problem specifically targeting males",
    "Video is exactly what the title presents",
    "Praises an aspect of a video game, with the video itself just being a neat gameplay clip",
    "Plays a game that supposedly ruins friendships, but their friendship is not ruined",
    "Posits that there is a deeper meaning to a popular piece event, but the video itself is a vague commentary/reaction video"
]