export const TAGLINES = [
  "Because everyone needs another daily.",
  "forsen",
  "Elephants have really long trunks.",
  "macGabriel100 was here.",
  "Wh-wha-what's going on?",
  "i guess",
  "Why is the rum gone?",
  "Because YouTube is where the poop is.",
  "Dinner blaster? I hardly know her!",
  "I have no strong feelings one way or the other.",
  "Where're they taking the hobbits to?",
  "To this day, no one knows why he's still getting hate.",
  "Doo yooh rhemnmmembhur vodka?",
  "Balla-da-li-di-la...",
  "What is that mysterious ticking noise...?",
  "FINISH HIM!",
  "And now back to George Lopez.",
  "Remember to rate 5 stars!",
  "FOV slider not included.",
  "Bob is building an army...",
  "I wonder what's for dinner?",
  "Weeaboos are not welcome.",
  "LOS!!!",
  "FIRST!",
  "Fegelein! Fegelein!",
  "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  "Gingers have souls!",
  "Today, we'll be talking about that PS triple.",
  "Don't use the dye.",
  "Will it blend?",
  "Doin' your mom since 2010.",
  "Girugamesh!",
  "Got any grapes?",
  "But, I'm not a rapper.",
  "I am Painis Cupcake.",
  "Song name?",
  "I am very hungry.",
  "Come on. Let's go find an octagon.",
  "Green is not a creative color.",
  "WE'LL DO IT LIVE!",
  "Our lawyers say 'YES! YES!'",
  "=3",
  "I'm on the weird side of... Wait a minute...",
  "hi, welcome to my utube tutorial.",
  "Music by Kevin MacLeod.",
  "You want this cake?",
  "BARRELS!",
  "I'm a lyrical spiritual miracle individual.",
  "Matei is highly intelligent.",
  "I'm 12 years old and what is this?",
  "Subscribed.",
  "*This tagline has received too many negative votes*",
  "Not fake. Possibly gay.",
  "op",
  "[Insert funny tagline here]",
  "In a perfect world, this site would not exist. But, this is not a perfect world."
]