export const TAGLINES = [
  "Because everyone needs another daily.",
  "forsen",
  "Elephants have really long trunks.",
  "macGabriel100 was here.",
  "Wh-wha-what's going on?",
  "i guess",
  "Why is the rum gone?",
  "Because YouTube is where the poop is.",
  "Dinner blaster? I hardly know her!",
  "I have no strong feelings one way or the other.",
  "Where they're taking the hobbits to, no one knows.",
  "To this day, no one knows why he's still getting hate.",
  "Doo yooh rhemnmmembhur vodka?",
  "Balla-da-li-di-la...",
  "What is that mysterious ticking noise...?",
  "FINISH HIM!",
  "And now back to George Lopez...",
  "Remember to rate 5 stars!",
  "Wazgul is?",
  "FOV slider not included.",
  "Bob is building an army...",
  "I wonder what's for dinner?",
  "DR OCTAGONAPUS, BLARGGGGGGGH!",
  "Weebs, out.",
  "Hi! I'ma draw ya!",
  "LOS!!!",
  "It's all Steiner's fault.",
  "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  "GINGERS HAVE SOULS!!!",
  "Today, we'll be talking about that PS triple.",
  "Don't use the dye.",
  "Will it blend?",
  "Doin' your mom since 2010.",
  "Girugamesh!",
  "Got any grapes?",
  "But, I'm not a rapper.",
  "I am Painis Cupcake.",
  "Song name?",
  "I am very hungry.",
  "WE FOUND AN OCTAGON!!!",
  "Green is not a creative color.",
  "WE'LL DO IT LIVE!",
  "Yes! Yes!",
  "=3",
  "hi, welcome to my utube tutorial.",
  "Music by Kevin MacLeod.",
  "1v1 me rust rn.",
  "You want this cake?",
  "BARRELS!",
  "I'm a lyrical spiritual miracle individual.",
  "Matei is highly intelligent."
]